### ISSUE TITLE
Dashboard widget to clear cache

### ISSUE THREAD

**Issue by Zmove** [Biz-mark/Quicksilver#1]
Hello,

Really nice to see some performance boost plugin for october CMS. I developped many sites with it, performances are OK but I could never decrease the TTFB below 800ms, which is quite high, even for small websites.

Hope to go below 500ms using static cache...

However, I have a feature request : The clients for which I develop websites are not developers and can't type artisan command to clear cache. It would be a great addition to be able to do that in a widget directly in the October CMS dashboard.

Do you think it could be possible ?

Best regards,

Alex

**Comment by FlusherDock1** [comment]
> Hope to go below 500ms using static cache...

With Quicksliver I get around 20 ~ 40 ms, check the configuration section in documentation to set it up properly.

> It would be a great addition to be able to do that in a widget directly in the October CMS dashboard.

Already working on it, will be available in the next update.

**Comment by ghost** [comment]
+1 for this, it would be really useful to have a nice clear cache widget in order to add it to our customers interface

**Comment by ghost** [comment]
Created a PR for this #3

**Comment by ghost** [comment]
Another possible solution (that could be better, but don't know if its possible) would be to include the static page cache clear to `php artisan cache:clear` command. We can suppose that people that want to clear the artisan cache want to clear static page cache also.

With that solution, we don't need to create a new widget to clear cache as there is already some modules that a widget for that.

**Comment by FlusherDock1** [comment]
@Zmove i just rolled new update, that has new ReportWidget in it with useful functionality
