### ISSUE TITLE
2.0 issues

### ISSUE THREAD

**Issue by amdad** [Biz-mark/Quicksilver#10]
Hello, 
Since 2.0 update. Plugin stopped to work correctly.  Pages are created in /page-cache but only homepage seems to load from there.  Can you post your whole clean October .htaccess, properly modified for v2.0? I guess maybe there is a problem. And I don't speak Russian to follow forum. 

Thanks!

**Comment by FlusherDock1** [comment]
Hi @amdad! Thanks for the issue, but i didn't see any same problems that you have. Are you using apache? Are your .htaccess configured correctly? Did you updated plugin correctly?

**Comment by TarasMykytka** [comment]
Hi, it's already fixed in PR #11

**Comment by FlusherDock1** [comment]
@amdad fixes merged to master. you can test it right now, update will be available in marketplace soon as testing completed.

**Comment by amdad** [comment]
@FlusherDock1  ~ ~ ~ IT FLIES NOW ! 
@TarasMykytka **Thank you** for your superinput!

Please _push it_ to marketplace.
And thanks for 2.0 configurable exceptions on backed. More better :)

**Comment by amdad** [comment]
Oh, sory, I originally tested it on October v1.0.472 and as I said, it went good.

But now I tried on v2.0.14, and nothing seems to work. Pages do not show up in /page-cache folder. But /combiner folder do. And it breaks css stylesheets. 

Did you tried it on October 2 @TarasMykytka?

**Comment by TarasMykytka** [comment]
@amdad , I didn't try October 2 at all. When I have project on v2, I'll test it for sure.

**Comment by amdad** [comment]
So indeed, we have some "2.0 issues" @FlusherDock1 ;)

**Comment by TarasMykytka** [comment]
@amdad , I've just fixed #14 those bug with combined assets for October 2. Now it works! :)

**Comment by amdad** [comment]
Yeah, @TarasMykytka but what about the rest of the plugin? Is it works for you?  Show me your htaccess if so :)
