### ISSUE TITLE
Encoding issue for cached pages

### ISSUE THREAD

**Issue by ghost** [Biz-mark/Quicksilver#2]
Hello,

Congratulation for your plugin, I could notice very big performance improvements, especially concerning TTFB.

However, I noticed a bug with character encoding. All accents are displayed weirdly, for example, the word : "réception" is displayed "rÃ©ceptions".

It's probably related to page encoding, I suggest you use UTF-8 for better support of special characters.

Best regards,

Alex

**Comment by FlusherDock1** [comment]
Hello, if you already fixed it for your project you can submit PR. if you didn't I will fix it soon. Thanks

**Comment by ghost** [comment]
Hi, I just posted to notify that bug, but unfortunately, I don't have time to investigate further at the moment.

**Comment by ghost** [comment]
Hmm, could get some time to investigate. The file encoding is correct if you add this in your meta : `<meta charset="utf-8">`

So I think it's not a real issue anymore and can be closed.
