### ISSUE TITLE
Fatal error after backend logout

### ISSUE THREAD

**Issue by ghost** [Biz-mark/Quicksilver#4]
Hello,

After installing this module, on a fresh install. When you logout the backend, you have an error : 

> Type error: Argument 2 passed to BizMark\Quicksilver\Classes\Middleware\CacheResponse::shouldCache() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in /plugins/bizmark/quicksilver/classes/middleware/CacheResponse.php on line 43

Quite critical here as you can't login anymore without commenting the if statement in line 43-45 in CacheResponse.php

**Comment by FlusherDock1** [comment]
Fixed in latest updated. Sorry for the long answer.
