### ISSUE TITLE
Generate Static HTML for anonymous users only

### ISSUE THREAD

**Issue by PubliAlex** [Biz-mark/Quicksilver#5]
Hello,

I noticed something really annoying with this module.

It actually cache static HTML file as it's viewed. This means it will cache and serv to everybody all administrative tools you can have on your frontend as a website administrator.

Here is a small example : Let's imagine you use the excellent [content editor plugin](https://octobercms.com/plugin/samuell-contenteditor) to manage your frontend texts. The page will be cached including that small blue pen on the top left corner of each pages. **Once cached, even anonymous visitors will see this pen, and they will see all others tools of special classes an administrator could have on a website frontend. This can lead to big UI and security issues.**

There are 2 things to do to correct that problem : 

- Be sure that, when you cache the page, you cache only anonymous version of pages (anonymous from backend, but also from users logged with the [user plugin](https://octobercms.com/plugin/rainlab-user))

- Serve cached page only for anonymous (people logged as backend admin, or frontend user should not see cached version)

This is what most (to not say all) cms I know do, cached pages are only made for anonymous users, to speedup page load. Once they are connected, pages are dynamically calculated.

Best regards,

Alex

**Comment by FlusherDock1** [comment]
Hi!

By configuring `.htaccess` of your webserver, all requests will not touch original octobercms `index.php`, and open `.html` files stored in storage, so we can't have any logic on this stage.

I will implement extra "if's" in shouldCache method, so it won't cache page if visitor logged in as backend admin or user plugin.

There are solution for you in your project right now. In the docs you can find example of extending `shouldCache` method in your own plugin. There you can write any custom logic you want.

Hope that helps.

**Comment by PubliAlex** [comment]
Hello,

Thank you for your answer. If I understand well, by adding extra "if's" in your shouldCache method, you can make sure you cache only pages of anonymous visitors, which is a good point.

But we also need to prevent to serve cached page to anonymous users only. When you are logged in as administrator, you want to see you frontend tools back, or when you are logged in as frontend user, you want to see your name or photo in the top right corned, confirming you are logged in... 

Without that, this plugin becom useless as soon as you have users. I understand that you can't add any logic to .htaccess, maybe this is the thing to change. Load octobercms just to do the necessary conditions : 

- if user is logged in (as frontend or backend user) > load page normally
- if user is anonymous > load cached .html file

I don't think it would have strong impact on page speed just by booting october the time to make this small condition. You could even create a extendable "shouldServe" method to let people add their own logic if needed, exactly like the shouldCache method. Another small improvement by doing like this. You don't need to modify your .htaccess file for each project using this plugin.

Let me know if you are ok with that and plan to modify the plugin that way. As it's absolute necessity to me, it will define if I have to create a fork or maybe help for a PR.

**Comment by PubliAlex** [comment]
Created a PR that add backend user check in shouldCache method #6, feel free to merge it.
